table:
  name: products
  schema: public
object_relationships:
  - name: supplier
    using:
      foreign_key_constraint_on: supplier_id
array_relationships:
  - name: orders_products
    using:
      foreign_key_constraint_on:
        column: product_id
        table:
          name: orders_products
          schema: public
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - supplier_id
        - category
        - description
        - name
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - supplier_id
        - category
        - description
        - name
      filter: {}
update_permissions:
  - role: user
    permission:
      columns:
        - id
        - supplier_id
        - category
        - description
        - name
      filter: {}
      check: {}
delete_permissions:
  - role: user
    permission:
      filter: {}
