table:
  name: users
  schema: public
array_relationships:
  - name: messages
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: messages
          schema: public
  - name: owner
    using:
      foreign_key_constraint_on:
        column: owner_id
        table:
          name: user_relationships
          schema: public
  - name: products
    using:
      foreign_key_constraint_on:
        column: supplier_id
        table:
          name: products
          schema: public
  - name: supplier
    using:
      foreign_key_constraint_on:
        column: supplier_id
        table:
          name: user_relationships
          schema: public
  - name: user_1
    using:
      foreign_key_constraint_on:
        column: user_id_1
        table:
          name: user_orders
          schema: public
  - name: user_2
    using:
      foreign_key_constraint_on:
        column: user_id_2
        table:
          name: user_orders
          schema: public
  - name: user_role
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: user_roles
          schema: public
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - email
        - name
        - uid
        - created_at
        - last_seen
        - last_typed
        - updated_at
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - email
        - name
        - uid
        - created_at
        - last_seen
        - last_typed
        - updated_at
      filter: {}
update_permissions:
  - role: user
    permission:
      columns:
        - id
        - email
        - name
        - uid
        - created_at
        - last_seen
        - last_typed
        - updated_at
      filter: {}
      check: {}
delete_permissions:
  - role: user
    permission:
      filter: {}
