table:
  name: products
  schema: public
object_relationships:
  - name: supplier
    using:
      foreign_key_constraint_on: supplier_id
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - supplier_id
        - category
        - description
        - name
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - supplier_id
        - category
        - description
        - name
      filter: {}
update_permissions:
  - role: user
    permission:
      columns:
        - id
        - supplier_id
        - category
        - description
        - name
      filter: {}
      check: {}
delete_permissions:
  - role: user
    permission:
      backend_only: false
      filter: {}
