table:
  name: users
  schema: public
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - email
        - name
        - uid
        - created_at
        - last_seen
        - updated_at
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - email
        - name
        - uid
        - created_at
        - last_seen
        - updated_at
      filter: {}
update_permissions:
  - role: user
    permission:
      columns:
        - id
        - email
        - name
        - uid
        - created_at
        - last_seen
        - updated_at
      filter: {}
      check: {}
delete_permissions:
  - role: user
    permission:
      backend_only: false
      filter: {}
